In [1]:
import cobra

In [2]:
import escher

In [3]:
from cobra import *

In [4]:
from escher import Builder

In [5]:
model = Model('Test')

In [6]:
GLC = Metabolite('GLC', compartment='c')
AA = Metabolite('AA', compartment='c')
Biomass = Metabolite('Biomass', compartment='c')

In [7]:
##### r0 : ======> GLC
r0 = Reaction('r0')
r0.name = 'R0'
r0.lower_bound = 1
r0.upper_bound = 1

In [8]:
##### r1 : GLC ======> AA
r1 = Reaction('r1')
r1.name = 'R1'
r1.lower_bound = 0
r1.upper_bound = 1000

In [9]:
##### r2 : AA ======> Biomass
r2 = Reaction('r2')
r2.name = 'R2'
r2.lower_bound = 0
r2.upper_bound = 1000

In [10]:
##### r3 : Biomass ======>
r3 = Reaction('r3')
r3.name = 'R3'
r3.lower_bound = 0
r3.upper_bound = 1000

In [11]:
r0.add_metabolites({GLC: 1})

In [12]:
r1.add_metabolites({GLC: -1, AA: 1})

In [13]:
r2.add_metabolites({AA: -9.09, Biomass: 1})

In [14]:
r3.add_metabolites({Biomass: -1})

In [15]:
model.add_reactions([r0, r1, r2, r3])

In [16]:
model.objective = 'r3'

In [17]:
model.optimize()

In [18]:
model.summary()

In [19]:
cobra.io.save_json_model(model, "task2.json")

In [20]:
builder = Builder(model_json="task2.json")

In [21]:
builder

Builder()